### ISSUE TITLE
Baguette Dissapeared - Food Crafting

### ISSUE THREAD

**Issue by nihanthkandimalla** [Serity/serity.github.io#1]
I crafted the baguette using all the delicious dishes, while i did get the pouch and could open it, the actual food with con +20 disappeared from my bag and i cant find it at all.

**Comment by Serity** [comment]
Man, I'm just a dataminer, I don't know these things. It should be listed in the food section of your bag. If it's not, and you're sure you didn't eat it, and you did craft the basic Baguette as well as getting a great success food pouch, file a bug report on the Moonlight Sculptor discord.
