### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by nihanthkandimalla** [Serity/serity.github.io#2]
Hi Serity, is there any chance of you updating the dump to a recent one.

Thanks for the dump :)

**Comment by Serity** [comment]
> 
> 
> Hi Serity, is there any chance of you updating the dump to a recent one.
> 
> Thanks for the dump :)

Sorries, I don't play the game anymore and have no intention of doing so :(

**Comment by nihanthkandimalla** [comment]
Sorry to disturb you again, is it possible to share the process of generating this data dump and sort it, so i can give it a try and also try to learn a new thing. :) . Again sorry for the bugging. :(
